name: UltimateRevenge
version: 7.6.0
api-version: 1.13
author: Royalpha
main: fr.royalpha.revenge.core.RevengePlugin
website: https://therenceforot.fr
commands:
  revenge:
    description: Revenge main command
    aliases: [rev]