name: Revenge
version: 7.3.1
api-version: 1.13
author: Asynchronous
softdepend: [PvPManager, DeathMessagesPrime]
main: fr.roytreo.revenge.core.RevengePlugin
website: http://roytreo28.ddns.net/asynchronous/
commands:
  revenge:
    description: Revenge main command
    aliases: [rev]