name: Revenge
version: 6.7
author: Asynchronous
softdepend: [PvPManager, DeathMessagesPrime]
main: fr.roytreo.revenge.core.RevengePlugin
website: http://roytreo28.ddns.net/home/
commands:
  revenge:
    description: Revenge main command
    aliases: [rev]