name: Revenge
version: 6.2
author: Asynchronous
softdepend: [PvPManager]
main: fr.roytreo.revenge.core.RevengePlugin
website: http://roytreo28.ddns.net/home/
commands:
  revenge:
    description: Revenge main command
    aliases: [rev]